import type { SimpleIcon } from 'simple-icons';
import {
  siAngular,
  siAndroid,
  siAnthropic,
  siApple,
  siBootstrap,
  siBun,
  siC,
  siClaude,
  siCplusplus,
  siCss,
  siCypress,
  siDart,
  siDeno,
  siDjango,
  siDocker,
  siDotnet,
  siElixir,
  siFastapi,
  siFigma,
  siFirebase,
  siFlask,
  siFlutter,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGo,
  siGodotengine,
  siGooglecloud,
  siGraphql,
  siHtml5,
  siIos,
  siJavascript,
  siJest,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siMongodb,
  siMysql,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siNpm,
  siNuxt,
  siOpenjdk,
  siPhp,
  siPnpm,
  siPostgresql,
  siPrisma,
  siPython,
  siR,
  siReact,
  siRedis,
  siRedux,
  siRuby,
  siRubyonrails,
  siRust,
  siSass,
  siScala,
  siSqlite,
  siSupabase,
  siSvelte,
  siSwift,
  siTailwindcss,
  siTauri,
  siTerraform,
  siTypescript,
  siUbuntu,
  siUnity,
  siVercel,
  siVite,
  siVitest,
  siVuedotjs,
  siWebpack,
  siYarn,
} from 'simple-icons';

/** Tecnologias que ganham logo ao aparecer como opção de um campo de seleção. */
const ICONS: SimpleIcon[] = [
  siAngular,
  siAndroid,
  siAnthropic,
  siApple,
  siBootstrap,
  siBun,
  siC,
  siClaude,
  siCplusplus,
  siCss,
  siCypress,
  siDart,
  siDeno,
  siDjango,
  siDocker,
  siDotnet,
  siElixir,
  siFastapi,
  siFigma,
  siFirebase,
  siFlask,
  siFlutter,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGo,
  siGodotengine,
  siGooglecloud,
  siGraphql,
  siHtml5,
  siIos,
  siJavascript,
  siJest,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siMongodb,
  siMysql,
  siNestjs,
  siNextdotjs,
  siNodedotjs,
  siNpm,
  siNuxt,
  siOpenjdk,
  siPhp,
  siPnpm,
  siPostgresql,
  siPrisma,
  siPython,
  siR,
  siReact,
  siRedis,
  siRedux,
  siRuby,
  siRubyonrails,
  siRust,
  siSass,
  siScala,
  siSqlite,
  siSupabase,
  siSvelte,
  siSwift,
  siTailwindcss,
  siTauri,
  siTerraform,
  siTypescript,
  siUbuntu,
  siUnity,
  siVercel,
  siVite,
  siVitest,
  siVuedotjs,
  siWebpack,
  siYarn,
];

/** Só letras, números e os símbolos que distinguem nomes ("C++"): "Vue.js", "vue js" e "VUEJS" viram a mesma chave. */
const key = (text: string): string => text.toLowerCase().replace(/[^a-z0-9+#]/g, '');

/** Outros nomes pelos quais a tecnologia costuma aparecer (a chave é o título do logo). */
const ALIASES: Record<string, string[]> = {
  'Node.js': ['node'],
  'Vue.js': ['vue'],
  'Next.js': ['next'],
  'Ruby on Rails': ['rails'],
  JavaScript: ['js'],
  TypeScript: ['ts'],
  Go: ['golang'],
  Kubernetes: ['k8s'],
  PostgreSQL: ['postgres'],
  MongoDB: ['mongo'],
  'Tailwind CSS': ['tailwind'],
  HTML5: ['html'],
  CSS: ['css3'],
  '.NET': ['dotnet'],
  OpenJDK: ['java'],
  'Google Cloud': ['gcp'],
  'GitHub Actions': ['actions'],
  'Godot Engine': ['godot'],
  iOS: ['swiftui'],
  NestJS: ['nest'],
};

const BY_KEY = new Map<string, SimpleIcon>();
for (const icon of ICONS) {
  BY_KEY.set(key(icon.title), icon);
  for (const alias of ALIASES[icon.title] ?? []) BY_KEY.set(key(alias), icon);
}

/** O logo da tecnologia que o texto nomeia (ex.: "Flutter", "react", "Node"); undefined se não for uma conhecida. */
export const techIcon = (text: string): SimpleIcon | undefined => BY_KEY.get(key(text));

/** Cor oficial da marca, ou a do texto quando ela some no fundo claro ou no escuro (GitHub, Next.js, Vercel...). */
export function techColor(icon: SimpleIcon): string {
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(icon.hex.slice(i, i + 2), 16) / 255) as [number, number, number];
  const luminance = 0.2126 * r + 0.7152 * g + 0.0722 * b;
  return luminance < 0.15 || luminance > 0.92 ? 'currentColor' : `#${icon.hex}`;
}
